config/routes.rb
Rails.application.routes.draw do
  get "blogs",    to: "static_pages#blogs"
  get "projects", to: "static_pages#projects"
  get "resume",   to: "static_pages#resume"
  get "cv",       to: "static_pages#resume"
  get "welcome",  to: "static_pages#about",    as: "about"

  get    "login",  to: "user_sessions#new"
  post   "login",  to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  # get  "register",      to: "user_registrations#new"
  # post "register/user", to: 'user_registrations#create'

  root "static_pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :positions, dependent: :destroy
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  has_many :skill_sets, dependent: :destroy
  has_many :skills, through: :skill_sets
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :skill_sets, dependent: :destroy
  has_many :positions, through: :skill_sets
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
  belongs_to :position
  belongs_to :skill
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  before_action :set_page_title
  # before_action :require_login # Add this to pages that require authentication to access

  private

  def not_authenticated
    redirect_to login_path, alert: t(:access_restricted)
  end

  def set_page_title
    @page_title = "Donovan's Web"
    @page_heading = "Welcome"
  end
end

app/controllers/static_pages_controller.rb
# StaticPagesController
class StaticPagesController < ApplicationController
  def about
    @page_heading = "Welcome"
  end

  def blogs
    @page_title = "Donovan's Blogs"
    @page_heading = "Blogs"
  end

  def resume
    @page_title = "Donovan's Resume"
    @page_heading = "Resume"
    @tags = %w[
      Linux BSD MacOS Windows iOS
      AWS GCP Heroku
      Ruby Ruby-on-Rails RSpec
      Python
      JAVA
      Apache nginx
      tmux screen
      ssh git GitHub
      shell bash zsh
      Docker
      firebase PostgreSQL
      javascript Reactjs react-jsx jest Node-js Electronjs
      HTML HAML
      sass CSS TailwindCSS
      acting improv team-building
    ].sort.uniq
  end

  def projects
    @page_title = "Donovan's Projects"
    @page_heading = "Projects"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @page_title = "Donovan: Login"
    @page_heading = "Please Login"
  end

  def create
    @user = login(params[:email], params[:password], true)

    if @user
      redirect_back_or_to(root_path, notice: "You have successfully logged in as #{current_user.email}")
    else
      redirect_to(login_path, status: :unprocessable_entity, alert: t(:auth_failed))
    end
  end

  def destroy
    logout
    redirect_to(root_path, status: :see_other, notice: t(:logged_out))
  end
end

app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
  include BetterHtml::Helpers

  def markdown(input)
    MarkdownParser.call(input)
  end
end

app/views/application/_header.html.erb
<header class="
  sticky
  top-0
  flex
  flex-row
  flex-auto
  justify-between
  border-b-2
  w-full
  h-16
  lg:h-20
  py-2
  px-4
  shadow
  lg:shadow-lg
  text-slate-300
  bg-slate-600
  border-slate-500
  dark:border-slate-900
  ">
  <div class="basis-1/3 grow text-left">
    <div id=logo class="
      fixed
      top-3
      lg:top-6
      left-4
      text-2xl
      lg:text-4xl
      -skew-y-3
      lg:-skew-y-6
      text-shadow
      lg:text-shadow-md
      text-blue-300
      dark:text-blue-400
      font-rock-salt
      ">
      Donovan C. Young
    </div>
  </div>
  <div class="basis-1/3 grow text-center hidden lg:flex justify-center items-center"><%= @page_heading %></div>
  <div class="basis-1/3 grow text-right flex justify-end items-center">
    <div class="hidden sm:block">
      Navbar Goes Here
    </div>
    <div class="sm:hidden">
      <i class="fa-solid fa-bars"></i>
      <%# TODO: Hamburger Menu Goes Here %>
    </div>
  </div>
</header>

app/views/elements/_alert.html.erb
<div class="flex items-center justify-center content-center bg-red-600 text-white text-sm font-bold px-4 py-3" role="alert">
  <i class="pr-2 fa-solid fa-triangle-exclamation"></i>
  <p><%= message %></p>
</div>

app/views/elements/_nav_menu.html.erb
<%= link_to "About Me", about_path, class: "p-2 #{action_name == 'about' && 'menu-active sm:menu-active-fancy'}", role: "menuitem" %>
<%= link_to "Blogs", blogs_path, class: "p-2 #{action_name == 'blogs' && 'menu-active sm:menu-active-fancy'}", role: "menuitem" %>
<%= link_to "Projects", projects_path, class: "p-2 #{action_name == 'projects' && 'menu-active sm:menu-active-fancy'}", role: "menuitem" %>

app/views/elements/_navbar.html.erb
<%# Display standard navbar on small+ screens %>
<div class="hidden sm:flex shrink-0 gap-2 font-rock-salt text-sm md:text-base text-blue-300 dark:text-blue-400">
  <%= render "elements/nav_menu" %>
</div>

<%# Display hamburger menu on xs screens %>
<div data-controller="view" class="inline-block sm:hidden">
  <button type="button" data-action="view#toggle" id="options-menu" aria-haspopup="true" aria-expanded="true">
    <i class="fa-solid fa-bars"></i>
  </button>

  <div data-view-target="toggleable" class="hidden absolute right-1 w-48 mt-2 bg-slate-500 shadow origin-top-right rounded-md ring-1 ring-black ring-opacity-5">
    <div class="grid grid-cols-1 divide-y divide-slate-600 text-blue-400 text-center font-rock-salt" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
      <%= render "elements/nav_menu" %>
    </div>
  </div>
</div>

app/views/elements/_notice.html.erb
<div class="flex items-center justify-center content-center bg-blue-500 text-white text-sm font-bold px-4 py-3" role="alert">
  <i class="pr-2 fa-solid fa-circle-info"></i>
  <p><%= message %></p>
</div>

app/views/elements/_social_links.html.erb
<ul class="flex flex-row content-center">
  <li><a class="px-2" href="mailto:me@donovanyoung.com?subject=Website%20Inquiry"><i class="fa-solid fa-at"></i></a></li>
  <li><a class="px-2" href="https://www.github.com/dyoung522"><i class="fa-brands fa-github"></i></a></li>
  <li><a class="px-2" href="https://stackoverflow.com/users/1794315/donovan"><i class="fa-brands fa-stack-overflow"></i></a></li>
  <li><a class="px-2" href="https://www.linkedin.com/in/dyoung522/"><i class="fa-brands fa-linkedin"></i></a></li>
</ul>

app/views/elements/_tags.html.erb
<% tags.each do |tag| %>
  <span class="inline-block py-1 px-2 m-1 text-xs rounded-full ring-2
    text-blue-700 dark:text-blue-200 bg-slate-300 dark:bg-slate-600 ring-blue-600">
    <%= tag %>
  </span>
<% end %>

app/views/home/index.html.erb
<section>
<p class="container paper">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing enim eu turpis egestas pretium. Molestie at elementum eu facilisis. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. At auctor urna nunc id. Cras semper auctor neque vitae tempus. Eros donec ac odio tempor orci dapibus. Purus gravida quis blandit turpis cursus in. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Massa tincidunt dui ut ornare lectus sit. Elementum nibh tellus molestie nunc non. Mi proin sed libero enim sed faucibus turpis in. Risus quis varius quam quisque id diam vel quam. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Feugiat scelerisque varius morbi enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Sodales ut etiam sit amet nisl. Gravida quis blandit turpis cursus.</p>
<p class="container">Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Egestas quis ipsum suspendisse ultrices. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Diam volutpat commodo sed egestas egestas. Urna duis convallis convallis tellus. Imperdiet massa tincidunt nunc pulvinar sapien et. Risus ultricies tristique nulla aliquet enim tortor at. Et ultrices neque ornare aenean euismod elementum. Metus aliquam eleifend mi in. In hac habitasse platea dictumst quisque sagittis purus sit amet. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Tincidunt praesent semper feugiat nibh sed. Placerat orci nulla pellentesque dignissim. Aenean et tortor at risus viverra adipiscing at. Maecenas pharetra convallis posuere morbi. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus.</p>
<p class="container">Arcu ac tortor dignissim convallis aenean et. Venenatis lectus magna fringilla urna porttitor. Nibh mauris cursus mattis molestie a iaculis. Urna duis convallis convallis tellus id interdum. Massa tempor nec feugiat nisl pretium fusce id. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Cursus in hac habitasse platea dictumst quisque. Purus non enim praesent elementum. Aliquet lectus proin nibh nisl condimentum id venenatis a. Fusce ut placerat orci nulla. Magna fermentum iaculis eu non diam phasellus vestibulum. Luctus accumsan tortor posuere ac. Pulvinar mattis nunc sed blandit.</p>
<p class="container paper">Libero justo laoreet sit amet cursus sit amet. Congue nisi vitae suscipit tellus mauris. In hac habitasse platea dictumst vestibulum rhoncus est. Cras ornare arcu dui vivamus. Urna cursus eget nunc scelerisque viverra mauris in. Blandit massa enim nec dui nunc mattis enim. Donec et odio pellentesque diam volutpat. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Urna molestie at elementum eu facilisis sed odio. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Tellus orci ac auctor augue. Purus non enim praesent elementum facilisis leo vel fringilla est. Lectus proin nibh nisl condimentum id venenatis a. Mattis aliquam faucibus purus in. Vulputate odio ut enim blandit.</p>
<p class="container">Gravida quis blandit turpis cursus in. Dui faucibus in ornare quam viverra orci. Est velit egestas dui id ornare arcu odio. Viverra aliquet eget sit amet tellus. Lectus quam id leo in vitae turpis massa. Tincidunt id aliquet risus feugiat in. Diam quis enim lobortis scelerisque. Laoreet sit amet cursus sit amet dictum sit amet justo. Tortor posuere ac ut consequat semper viverra nam libero justo. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Ante metus dictum at tempor commodo. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Ornare massa eget egestas purus. Elementum tempus egestas sed sed risus pretium. Turpis nunc eget lorem dolor sed. Nibh tellus molestie nunc non blandit. Malesuada fames ac turpis egestas integer.</p>
</section>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <aside>
    <%= render "elements/#{flash_type}", message: %>
  </aside>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="
  fixed
  bottom-0
  z-50
  w-full
  max-h-20
  flex
  flex-row
  flex-auto
  justify-between
  py-2
  px-4
  text-slate-700
  dark:text-slate-300
  bg-slate-200
  dark:bg-slate-800
  border-t-2
  border-slate-300
  dark:border-slate-900
  ">
  <div class="basis-1/3 grow text-left text-sm flex flex-row justify-start items-center">
    <div id="footer-left" class="pr-2">Contact Me:</div>

    <nav>
      <div class="text-lg">
        <%= render "elements/social_links" %>
      </div>
    </nav>
  </nav>
  <div id="footer-center" class="basis-1/3 grow text-center text-sm hidden lg:block"></div>
  <div id="footer-right" class="basis-1/3 grow text-right text-sm hidden sm:flex flex-col justify-end items-end content-center">
    <div class="text-slate-300">
      <% if current_user %>
        <span class="mr-1">Logged in as <%= current_user.email %></span><i class="fa-solid fa-arrow-right"></i>
        <%= link_to "logout", logout_path, id: "logout-link", data: { "turbo-method": :delete } %>
      <% else %>
        <%= link_to "Member login", login_path, id: "login-link" %>
      <% end %>
    </div>
    <div data-controller="footer-info" data-footer-info-rails-version-value="<%= Rails.version %>"></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="
  sticky
  top-0
  z-50
  w-full
  h-16
  lg:h-20
  py-2
  px-4
  shadow
  lg:shadow-lg
  text-slate-700
  dark:text-slate-300
  bg-slate-300
  dark:bg-slate-900
  border-b-2
  border-slate-300
  dark:border-slate-900
  ">
  <div class="flex flex-row flex-auto content-center justify-between w-full lg:w-4/5 h-full mx-auto">
    <div id="header-left" class="basis-1/3 grow shrink-0 text-left">
      <div id="logo" class="
        relative
        top-0
        sm:pt-2
        lg:pt-4
        w-fit
        lg:top-0
        left-4
        text-lg
        sm:text-xl
        lg:text-2xl
        xl:text-4xl
        -skew-y-3
        lg:-skew-y-6
        text-shadow
        text-blue-300
        dark:text-blue-400
        font-rock-salt
        ">
        <%= link_to "Donovan C. Young", root_path %>
      </div>
    </div>
    <div id="header-center" class="text-center hidden lg:flex justify-center items-center font-rock-salt text-2xl"><%= @page_heading %></div>
    <div id="header-right" class="basis-1/3 grow shrink-0 text-right flex justify-end items-center content-center"><%= render "elements/navbar" %></div>
  </div>
</header>
<div id="header-center-small" class="block text-center w-full py-1 lg:hidden text-lg font-rock-salt text-slate-300 bg-slate-500"><%= @page_heading %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Mono&family=Roboto+Slab&family=Rock+Salt&display=swap">

    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path("apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= image_path("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= image_path("favicon-16x16.png") %>">
    <link rel="manifest" href="<%= asset_path("site.webmanifest") %>">

    <script src="https://kit.fontawesome.com/0163082c10.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="min-h-screen bg-circuit-board-light dark:bg-circuit-board-dark bg-slate-200 dark:bg-slate-800 text-slate-800 dark:text-slate-300">
    <div id="page">
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <div id="main" class="prose prose-slate dark:prose-invert max-w-none mx-auto mb-20 px-2 lg:px-4 lg:w-10/12">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/elements/_header.html.erb
<header class="
  sticky
  top-0
  flex
  flex-row
  flex-auto
  justify-between
  border-b-2
  w-full
  h-16
  lg:h-20
  py-2
  px-4
  shadow
  lg:shadow-lg
  text-slate-300
  bg-slate-600
  border-slate-500
  dark:border-slate-900
  ">
  <div class="basis-1/3 grow text-left">
    <div id=logo class="
      fixed
      top-3
      lg:top-6
      left-4
      text-2xl
      lg:text-4xl
      -skew-y-3
      lg:-skew-y-6
      text-shadow
      lg:text-shadow-md
      text-blue-300
      dark:text-blue-400
      font-rock-salt
      ">
      <%= link_to "Donovan C. Young", root_path %>
    </div>
  </div>
  <div class="basis-1/3 grow text-center hidden lg:flex justify-center items-center font-rock-salt text-2xl"><%= @page_heading %></div>
  <div class="basis-1/3 grow text-right flex justify-end items-center content-center"><%= render "layouts/elements/navbar" %></div>
</header>
<div class="block text-center w-full py-1 lg:hidden text-lg font-rock-salt text-slate-300 bg-slate-500"><%= @page_heading %></div>

app/views/layouts/elements/_navbar.html.erb
<nav class="hidden sm:flex gap-5 font-rock-salt text-lg text-blue-300 dark:text-blue-400">
  <div class=<%= action_name == "welcome" && "text-blue-500" %> ><%= link_to "Home", welcome_path %></div>
  <div class=<%= action_name == "about" && "text-blue-500" %> ><%= link_to "About Me", about_path %></div>
  <div class=<%= action_name == "blog" && "text-blue-500" %> ><%= link_to "Blog", blog_path %></div>
</nav>

<%# Display hamburger menu on small screens %>
<div class="sm:hidden">
  <i class="fa-solid fa-bars"></i>
  <%# TODO: Hamburger Menu Goes Here %>
</div>

app/views/static_pages/_resume_experience.html.erb
<section class="">
  <div class="sm:text-lg font-bold text-blue-500 block sm:flex sm:flex-row sm:gap-2 justify-start italic font-serif pb-2">

    <% if local_variables.include?(:start_date) %>
      <div>
        <%= start_date %>&nbsp;

        <% if local_variables.include?(:end_date) %>
          <i class="fa-solid fa-arrow-right text-sm"></i>
          &nbsp;
          <%= end_date %>
        <% end %>
      </div>
    <% end %>

    <% if local_variables.include?(:title) %>
      <div class="hidden sm:flex">&mdash;</div>
      <div class=""><%= title %></div>
    <% end %>

    <% if local_variables.include?(:company) %>
      <div class="hidden sm:flex">&mdash;</div>
      <div class=""><%= company %></div>
    <% end %>
  </div>

  <% if local_variables.include?(:tags) %>
    <%= render "elements/tags", tags: %>
  <% end %>

  <% if yield.presence %>
    <% if local_variables.include?(:always_show) && always_show == true %>
      <%= yield %>
    <% else %>
      <div data-controller="height" class="">
        <button type="button" data-action="height#toggle" aria-haspopup="true" aria-expanded="true" class="pt-5 text-blue-500 hover:text-blue-600 font-bold">
          Click to view details
        </button>

        <div data-height-target="toggleable" class="transition-max-height duration-300 ease-in-out overflow-hidden max-h-0">
          <%= yield %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/static_pages/about.html.erb
<section>
  <div class="container paper sm:mt-32 text-sm sm:text-md lg:text-lg font-serif">
    <%= image_tag "headshot_circle_transparant.png",
        alt: "Photo of Donovan",
        class: "float-left h-24 sm:h-56 mx-4 sm:mx-8 sm:-ml-20 sm:-mt-20 rotate-12 sm:shadow-2xl shadow-black dark:shadow-white rounded-full bg-white" %>
    <%= markdown(File.read("app/views/static_pages/about_me.md")) %>
    <p>Thanks for stopping by,</p>
    <p class="text-right sm:text-left pl-4">&mdash;Donovan</p>
  </div>
</section>

app/views/static_pages/blog.html.erb
<div class="mx-auto mt-16 text-center text-xl">Coming Soon</div>

app/views/static_pages/blogs.html.erb
<div class="mx-auto mt-16 text-center text-xl">Coming Soon</div>

app/views/static_pages/projects.html.erb
<div class="mx-auto mt-16 text-center text-xl">Coming Soon</div>

app/views/user_sessions/new.html.erb
<div id="login-page" class="space-y-6 sm:space-y-5 mt-20">
  <%= form_with(model: @user, url: login_path, method: :post) do |form| %>
    <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:pt-5">
      <%= form.label :email, class: "block sm:text-right text-sm font-bold sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <%= form.text_field :email, class: "max-w-lg p-2 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md text-slate-800" %>
      </div>
    </div>

    <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:pt-5">
      <%= form.label :password, class: "block sm:text-right text-sm font-bold sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <%= form.password_field :password, class: "max-w-lg p-2 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md text-slate-800" %>
      </div>
    </div>

    <div class="sm:grid sm:grid-cols-2 sm:gap-4 sm:items-start sm:justify-items-center sm:pt-5">
      <div class="mt-1 py-1 px-2 w-24 ring-2 ring-blue-300 bg-blue-600 rounded sm:mt-0 sm:col-span-2 sm:text-center">
        <%= form.submit "Login", id: "sign-in-button" %>
      </div>
    </div>
  <% end %>
</div>